const catalogue = [
    
    { id:"0001", 
    category:"libreria",
    title:"Lapicera azul", 
    description:"Lapicera azul trazo fino. Precisión al escribir. Alta durabilidad.",
    brand:"Filgo",
    price:50, 
    pictureUrl:"../assets/lapicera-azul.png", 
    stock:5 },

    { id:"0002", 
    category:"libreria", 
    title:"Lapicera roja", 
    description:"Lapicera roja trazo fino. Precisión al escribir. Alta durabilidad.",
    brand:"Filgo",
    price:50, 
    pictureUrl:"../assets/lapicera-roja.png", 
    stock:8 },

    { id:"0003", 
    category:"libreria", 
    title:"Lápiz", 
    description:"Lapiz blando, de trazo medio. Ideal para aprender a escribir. Fácil de borrar.",
    brand:"Maped",
    price:45, 
    pictureUrl:"../assets/lapiz.png", 
    stock:10 },

    { id:"0004", 
    category:"libreria", 
    title:"Caja de 36 colores",     
    description:"Caja de 36 colores, de trazo grueso. Excelente calidad.",
    brand:"Maped",
    price:450, 
    pictureUrl:"../assets/caja-36-colores.png", 
    stock:7 },
    
    { id:"0005", 
    category:"libreria", 
    title:"Set de 4 resaltadores", 
    description:"Set de 4 resaltadores. Color amarillo, naranja, fucsia y verde.",
    brand:"Maped",
    price:230, 
    pictureUrl:"../assets/set-4-resaltadores.png", 
    stock:6 },

    { id:"0006", 
    category:"libreria", 
    title:"Canopla marrón y naranja", 
    description:"Canopla tipo tubo, con costuras reforzadas. Color marrón, con detalles en naranja.",
    brand:"Lulens",
    price:310, 
    pictureUrl:"../assets/canopla-marron-naranja.png", 
    stock:9 },
    
    { id:"0007", 
    category:"lanas", 
    title:"Ovillo de lana azul", 
    description:"Ovillo de lana azul de 10 m de largo. Textura suave y color brillante.",
    brand:"La Tejedora",
    price:599, 
    pictureUrl:"../assets/ovillo-lana-azul.png", 
    stock:12 },
    
    { id:"0008", 
    category:"merceria", 
    title:"Set de 6 hilos para coser", 
    description:"Set de 6 hilos para coser tamaño grande. Color rosa, lila, verde, amarillo, rojo y verde.",
    brand:"La Tejedora",
    price:470, 
    pictureUrl:"../assets/set-6-hilos.png", 
    stock:14 },
    
    { id:"0009", 
    category:"jugueteria", 
    title:"Mono Lulo", 
    description:"Mono de peluche. Muy suave. Excelente calidad. Detalles y terminaciones premium.",
    brand:"Mis Animalitos",
    price:1299, 
    pictureUrl:"../assets/mono-de-peluche.png", 
    stock:3 },
    
    { id:"0010", 
    category:"jugueteria", 
    title:"Bloques de madera", 
    description:"Set de cubos de madera para apilar. Terminaciones delicadas. Ideal para la primera infancia.",
    brand:"Kiddies",
    price:599, 
    pictureUrl:"../assets/bloques-de-madera.png", 
    stock:9 },
    
    { id:"0011", 
    category:"lanas", 
    title:"Ovillo de lana roja", 
    description:"Ovillo de lana roja de 8 m de largo. Textura suave y color brillante.",
    brand:"La Tejedora",
    price:499, 
    pictureUrl:"../assets/ovillo-lana-roja.png", 
    stock:7 },

    { id:"0012", 
    category:"merceria", 
    title:"Bobina de hilo sisal", 
    description:"Bobina de hilo sisal para manualidades, de 10 m de largo.",
    brand:"Marucha",
    price:499, 
    pictureUrl:"../assets/bobina-hilo-sisal.png", 
    stock:4 },

    { id:"0013", 
    category:"lanas", 
    title:"Bobina de hilo para tejer beige", 
    description:"Bobina de hilo para tejer beige de 12 m de largo. Calidad premium.",
    brand:"La Tejedora",
    price:799, 
    pictureUrl:"../assets/bobina-hilo-tejer.png", 
    stock:6 },

    { id:"0014", 
    category:"merceria", 
    title:"Centímetro", 
    description:"Centímetro de plástico, de 1,5 m de largo,",
    brand:"Marucha",
    price:249, 
    pictureUrl:"../assets/centimetro.png", 
    stock:12 },

    { id:"0015", 
    category:"jugueteria", 
    title:"Grua mini", 
    description:"Grua de plástico, muy resistente. Alto de 15 cm.",
    brand:"Kiddies",
    price:699, 
    pictureUrl:"../assets/grua-mini.png", 
    stock:17 },

    { id:"0016", 
    category:"jugueteria", 
    title:"Avioncito", 
    description:"Avioncito de plástico, con colores brillantes y hélice.",
    brand:"Kiddies",
    price:649, 
    pictureUrl:"../assets/avioncito.png", 
    stock:13 },

    { id:"0017", 
    category:"jugueteria", 
    title:"Set de chiches para el agua", 
    description:"Set de elefante, pato y foca, en plástico blando. Con chillido. Ideal para el momento del baño.",
    brand:"RoPlast",
    price:649, 
    pictureUrl:"../assets/set-chiches-agua.png", 
    stock:10 },

    { id:"0018", 
    category:"jugueteria", 
    title:"Muñeca de tela", 
    description:"Muñeca confeccionada en tela. Vestidito cuadrillé y pelo rubio.",
    brand:"Valery",
    price:999, 
    pictureUrl:"../assets/muñeca-tela.png", 
    stock:9 },

];

const GetFetch = new Promise((resolve, reject) =>{
    setTimeout(() =>{
        resolve(catalogue)
    }, 2000)
})

export default GetFetch